// packages/agros-example/demos/vue/src/modules/lorem/Lorem.vue
<template>
    <div>Welcome to Lorem page!</div>
</template>

<script>
import { getContainer } from '@agros/app';
import { LoremService } from './lorem.service';

const Lorem = {
    mounted() {
        const container = getContainer(Lorem);
        const loremService = container.get<LoremService>(LoremService);
        loremService.sayHello();
    }
};

export default Lorem;
</script>

// packages/agros-example/src/modules/lorem/Lorem.tsx
import { FC } from 'react';
import {
    forwardContainer,
    useEffect,
    memo,
} from '@agros/app';
import { LoremService } from './lorem.service';

const Lorem: FC = forwardContainer(({ container }) => {
    const loremService = container.get<LoremService>(LoremService);

    useEffect(() => {
        loremService.sayHello();
    }, []);

    return (
        <div>Welcome to Lorem page!</div>
    );
});

export default memo(Lorem);
