// packages/agros-example/demos/react/src/modules/foo/Foo.tsx
import React from '@agros/platform-react/lib/react';
import { getContainer } from '@agros/app';
import { Outlet } from '@agros/platform-react/lib/react-router-dom';
import { BarComponent } from '../bar/bar.component';
import { BarService } from '../bar/bar.service';
import { FooService } from './foo.service';

const Foo: React.FC = () => {
    const container = getContainer(Foo);
    const Bar = container.get<React.FC<React.PropsWithChildren<{ used: string }>>>(BarComponent);
    const fooService = container.get<FooService>(FooService);
    const barService = container.get<BarService>(BarService);

    React.useEffect(() => {
        fooService.logHello();
        barService.sayHello();
    }, []);

    return (
        <>
            <div>Agros is working!</div>
            {Bar && <Bar used="foo.module.ts" />}
            <Outlet />
        </>
    );
};

export default Foo;

// packages/agros-example/demos/svelte/src/modules/foo/Foo.svelte
<script>
import { getContainer } from '@agros/app';
import { BarComponent } from '../bar/bar.component';
import { BarService } from '../bar/bar.service';
import { FooService } from './foo.service';
import { RouterOutlet } from '@agros/platform-svelte/lib/svelte-router';

const container = getContainer();
const fooService = container.get<FooService>(FooService);
const barService = container.get<BarService>(BarService);
fooService.logHello();
barService.sayHello();
</script>

<div>
    <div>Agros is working!</div>
    <svelte:component this={container.get(BarComponent)} used="foo.module.ts" />
    <RouterOutlet />
</div>
