// packages/agros-example/demos/vue/src/modules/lorem/Lorem.vue
<template>
    <div>Welcome to Lorem page!</div>
</template>

<script>
import { getContainer } from '@agros/app';
import { LoremService } from './lorem.service';

const Lorem = {
    mounted() {
        const container = getContainer(Lorem);
        const loremService = container.get<LoremService>(LoremService);
        loremService.sayHello();
    }
};

export default Lorem;
</script>

// packages/agros-example/demos/react/src/modules/lorem/Lorem.tsx
import { getContainer } from '@agros/app';
import React from '@agros/platform-react/lib/react';
import { LoremService } from './lorem.service';

const Lorem: React.FC = () => {
    const container = getContainer();
    const loremService = container.get<LoremService>(LoremService);

    React.useEffect(() => {
        loremService.sayHello();
    }, []);

    return (
        <div>Welcome to Lorem page!</div>
    );
};

export default React.memo(Lorem);
